In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [2]:
# Optuna는 딥러닝에서는 너무 느려서 안쓰고, 머신러닝에서 주로 쓴다, 최대 장점은 잘 몰라도 하이퍼 파라미터를 잘 찾아준다.
!pip install optuna

In [3]:
!pip install catboost

In [4]:
!pip install pycaret

In [5]:
#데이터 분석 4종 세트
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# 모델들, 성능 평가
# (저는 일반적으로 정형데이터로 머신러닝 분석할 때는 이 2개 모델은 그냥 돌려봅니다. 특히 RF가 테스트하기 좋습니다.)
from lightgbm.sklearn import LGBMRegressor
from xgboost.sklearn import XGBRegressor
from catboost import CatBoostRegressor

# 상관관계 분석, VIF : 다중공산성 제거
from statsmodels.stats.outliers_influence import variance_inflation_factor

# KFold(CV), partial : optuna를 사용하기 위함
from sklearn.model_selection import KFold
from functools import partial

# hyper-parameter tuning을 위한 라이브러리, optuna
import optuna

# AutoML - pycaret
from pycaret.regression import *

In [6]:
# 코랩에서 한글 쓰기!
!sudo apt-get install -y fonts-nanum # 나눔 글꼴
!sudo fc-cache -fv
!rm ~/.cache/matplotlib -rf

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  fonts-nanum
0 upgraded, 1 newly installed, 0 to remove and 15 not upgraded.
Need to get 10.3 MB of archives.
After this operation, 34.1 MB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu jammy/universe amd64 fonts-nanum all 20200506-1 [10.3 MB]
Fetched 10.3 MB in 1s (6,971 kB/s)
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 78, <> line 1.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletype
dpkg-preconfigure: unable to re-open stdin: 
Selecting previously unselected package fonts-nanum.
(Reading database ... 120899 files and dire

In [51]:
import matplotlib as mpl
# Colab 의 한글 폰트 설정
plt.rc('font', family='NanumBarunGothic')
# 유니코드에서  음수 부호설정
mpl.rc('axes', unicode_minus=False) # False로 해야 -부호가 안깨짐

In [8]:
train = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/data/deacu_car_accident/train_all.csv")
test = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/data/deacu_car_accident/test.csv")

In [9]:
train

ID   요일 기상상태 노면상태  사고유형 사고유형 - 세부분류  \
0       COUNTRYWIDE_ACCIDENT_000000  화요일   맑음   건조  차대사람         횡단중   
1       COUNTRYWIDE_ACCIDENT_000001  화요일   맑음   건조   차대차          기타   
2       COUNTRYWIDE_ACCIDENT_000002  화요일   맑음   건조   차대차        측면충돌   
3       COUNTRYWIDE_ACCIDENT_000003  화요일   맑음   건조  차대사람         횡단중   
4       COUNTRYWIDE_ACCIDENT_000004  화요일   맑음   건조   차대차        측면충돌   
...                             ...  ...  ...  ...   ...         ...   
616550               ACCIDENT_39604  금요일   맑음   건조   차대차        측면충돌   
616551               ACCIDENT_39605  금요일   맑음   건조   차대차        측면충돌   
616552               ACCIDENT_39606  금요일   맑음   건조   차대차        측면충돌   
616553               ACCIDENT_39607  금요일   맑음   건조   차대차          추돌   
616554               ACCIDENT_39608  금요일   맑음   건조   차대차        측면충돌   

             법규위반 가해운전자 차종 가해운전자 성별 가해운전자 연령  ... 주야구분 피해운전자 연령대 피해운전자 구분  \
0       보행자보호의무위반       승용        남      26세  ...   야간       40대       일반   
1       직진우회전진행방해       승용        남      54세  ...   야간       20대       일반   
2            신호위반       승용        여      57세  ...   야간       10대       일반   
3       보행자보호의무위반       승용        여      65세  ...   야간       10대       일반   
4            신호위반       승용        여      74세  ...   야간       50대       일반   
...           ...      ...      ...      ...  ...  ...       ...      ...   
616550       신호위반       승용        여      52세  ...   야간       20대       일반   
616551    안전거리미확보       승용        여      60세  ...   야간       50대       일반   
616552  교차로운행방법위반       승용        남      60세  ...   야간       70대       고령   
616553    안전운전불이행       승용        남      40세  ...   야간       50대       일반   
616554    안전운전불이행       승용        남      27세  ...   야간       30대       일반   

       가해운전자 연령대 가해운전자 구분   시, 도  도로형태1       도로형태2  계절  사고 규모  
0            20대       일반  서울특별시   교차로     교차로횡단보도내  겨울     소형  
1            50대       일반    경기도   교차로         교차로안  겨울     소형  
2            50대       일반    경기도   교차로         교차로안  겨울     중형  
3            60대       고령    경기도    기타           기타  겨울     중형  
4            70대       고령  인천광역시   교차로         교차로안  겨울     중형  
...          ...      ...    ...    ...         ...  ..    ...  
616550       50대       일반  대구광역시   교차로         교차로안  겨울     소형  
616551       60대       고령  대구광역시   단일로           기타  겨울     소형  
616552       60대       고령  대구광역시   교차로         교차로안  겨울     중형  
616553       40대       일반  대구광역시    기타           기타  겨울     소형  
616554       20대       일반  대구광역시   단일로    지하차도(도로)내  겨울     중형  

[616555 rows x 33 columns]

In [10]:
test

ID           사고일시   요일 기상상태              시군구         도로형태  \
0      ACCIDENT_39609  2022-01-01 01  토요일   맑음     대구광역시 수성구 상동   교차로 - 교차로안   
1      ACCIDENT_39610  2022-01-01 01  토요일   맑음    대구광역시 수성구 지산동     단일로 - 기타   
2      ACCIDENT_39611  2022-01-01 04  토요일   맑음  대구광역시 수성구 수성동2가   교차로 - 교차로안   
3      ACCIDENT_39612  2022-01-01 04  토요일   맑음    대구광역시 수성구 신매동     단일로 - 기타   
4      ACCIDENT_39613  2022-01-01 06  토요일   맑음    대구광역시 달서구 감삼동   교차로 - 교차로안   
...               ...            ...  ...  ...              ...          ...   
10958  ACCIDENT_50567  2022-12-31 18  토요일   맑음     대구광역시 남구 대명동     단일로 - 터널   
10959  ACCIDENT_50568  2022-12-31 18  토요일   맑음    대구광역시 수성구 시지동     단일로 - 기타   
10960  ACCIDENT_50569  2022-12-31 20  토요일   맑음    대구광역시 수성구 연호동     단일로 - 기타   
10961  ACCIDENT_50570  2022-12-31 20  토요일   맑음    대구광역시 수성구 범물동  교차로 - 교차로부근   
10962  ACCIDENT_50571  2022-12-31 21  토요일   맑음     대구광역시 동구 효목동  교차로 - 교차로부근   

      노면상태  사고유형  
0       건조  차대사람  
1       건조  차대사람  
2       건조   차대차  
3       건조   차대차  
4       건조   차대차  
...    ...   ...  
10958   건조   차대차  
10959   건조   차대차  
10960   건조   차대차  
10961   건조   차대차  
10962   건조   차대차  

[10963 rows x 8 columns]

## Data Wrangiling

In [11]:
def wrangiling(data_set):
    print("==================")
    print("       Shape      ")
    print("==================")

    display(data_set.shape)

    print("==================")
    print("        Info      ")
    print("==================")

    display(data_set.info())

    print("==================")
    print("      Columns     ")
    print("==================")

    display(data_set.columns)

    print("==================")
    print("        NaN       ")
    print("==================")

    display(data_set.isna().sum())

    print("==================")
    print("    Duplicated    ")
    print("==================")

    display(data_set[data_set.duplicated()])

    print("==================")
    print("    Description   ")
    print("==================")

    display(data_set.describe())

    print("==================")
    print("      Unique      ")
    print("==================")

    display(data_set.nunique())

In [12]:
wrangiling(train)

       Shape      


(616555, 33)

        Info      
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 616555 entries, 0 to 616554
Data columns (total 33 columns):
 #   Column       Non-Null Count   Dtype 
---  ------       --------------   ----- 
 0   ID           616555 non-null  object
 1   요일           616555 non-null  object
 2   기상상태         616555 non-null  object
 3   노면상태         616555 non-null  object
 4   사고유형         616555 non-null  object
 5   사고유형 - 세부분류  616555 non-null  object
 6   법규위반         616555 non-null  object
 7   가해운전자 차종     616555 non-null  object
 8   가해운전자 성별     616555 non-null  object
 9   가해운전자 연령     616555 non-null  object
 10  가해운전자 상해정도   616555 non-null  object
 11  피해운전자 차종     615564 non-null  object
 12  피해운전자 성별     615564 non-null  object
 13  피해운전자 연령     615564 non-null  object
 14  피해운전자 상해정도   615564 non-null  object
 15  사망자수         616555 non-null  int64 
 16  중상자수         616555 non-null  int64 
 17  경상자수         616555 non-null  int64 
 18  부상자수         616555 non-n

None

      Columns     


Index(['ID', '요일', '기상상태', '노면상태', '사고유형', '사고유형 - 세부분류', '법규위반', '가해운전자 차종',
       '가해운전자 성별', '가해운전자 연령', '가해운전자 상해정도', '피해운전자 차종', '피해운전자 성별',
       '피해운전자 연령', '피해운전자 상해정도', '사망자수', '중상자수', '경상자수', '부상자수', 'ECLO', '월',
       '일', '시간', '주야구분', '피해운전자 연령대', '피해운전자 구분', '가해운전자 연령대', '가해운전자 구분',
       '시, 도', '도로형태1', '도로형태2', '계절', '사고 규모'],
      dtype='object')

        NaN       


ID               0
요일               0
기상상태             0
노면상태             0
사고유형             0
사고유형 - 세부분류      0
법규위반             0
가해운전자 차종         0
가해운전자 성별         0
가해운전자 연령         0
가해운전자 상해정도       0
피해운전자 차종       991
피해운전자 성별       991
피해운전자 연령       991
피해운전자 상해정도     991
사망자수             0
중상자수             0
경상자수             0
부상자수             0
ECLO             0
월                0
일                0
시간               0
주야구분             0
피해운전자 연령대        0
피해운전자 구분         0
가해운전자 연령대        0
가해운전자 구분         0
시, 도             0
도로형태1            0
도로형태2            0
계절               0
사고 규모            0
dtype: int64

    Duplicated    


Empty DataFrame
Columns: [ID, 요일, 기상상태, 노면상태, 사고유형, 사고유형 - 세부분류, 법규위반, 가해운전자 차종, 가해운전자 성별, 가해운전자 연령, 가해운전자 상해정도, 피해운전자 차종, 피해운전자 성별, 피해운전자 연령, 피해운전자 상해정도, 사망자수, 중상자수, 경상자수, 부상자수, ECLO, 월, 일, 시간, 주야구분, 피해운전자 연령대, 피해운전자 구분, 가해운전자 연령대, 가해운전자 구분, 시, 도, 도로형태1, 도로형태2, 계절, 사고 규모]
Index: []

[0 rows x 33 columns]

    Description   


사망자수           중상자수           경상자수           부상자수  \
count  616555.000000  616555.000000  616555.000000  616555.000000   
mean        0.011838       0.289119       1.096877       0.089857   
std         0.112322       0.543976       1.046529       0.367386   
min         0.000000       0.000000       0.000000       0.000000   
25%         0.000000       0.000000       0.000000       0.000000   
50%         0.000000       0.000000       1.000000       0.000000   
75%         0.000000       1.000000       1.000000       0.000000   
max         6.000000      31.000000      41.000000      47.000000   

                ECLO              월              일             시간  
count  616555.000000  616555.000000  616555.000000  616555.000000  
mean        4.944469       6.680921      15.833337      13.841388  
std         3.570352       3.402979       8.762532       5.622692  
min         1.000000       1.000000       1.000000       0.000000  
25%         3.000000       4.000000       8.000000      10.000000  
50%         3.000000       7.000000      16.000000      14.000000  
75%         6.000000      10.000000      23.000000      18.000000  
max       245.000000      12.000000      31.000000      23.000000

      Unique      


ID             616555
요일                  7
기상상태                6
노면상태                7
사고유형                4
사고유형 - 세부분류        15
법규위반               11
가해운전자 차종           12
가해운전자 성별            3
가해운전자 연령           98
가해운전자 상해정도          6
피해운전자 차종           13
피해운전자 성별            3
피해운전자 연령          100
피해운전자 상해정도          6
사망자수                7
중상자수               19
경상자수               35
부상자수               21
ECLO              106
월                  12
일                  31
시간                 24
주야구분                2
피해운전자 연령대           9
피해운전자 구분            3
가해운전자 연령대           9
가해운전자 구분            3
시, 도               18
도로형태1               5
도로형태2              11
계절                  4
사고 규모               3
dtype: int64

In [13]:
def unique_cols(data_set):
    for col in data_set.columns[:]:
        print(f" == {col} ==")
        display(data_set[col].unique())

In [14]:
unique_cols(data_set=train)

 == ID ==


array(['COUNTRYWIDE_ACCIDENT_000000', 'COUNTRYWIDE_ACCIDENT_000001',
       'COUNTRYWIDE_ACCIDENT_000002', ..., 'ACCIDENT_39606',
       'ACCIDENT_39607', 'ACCIDENT_39608'], dtype=object)

 == 요일 ==


array(['화요일', '수요일', '목요일', '금요일', '토요일', '일요일', '월요일'], dtype=object)

 == 기상상태 ==


array(['맑음', '흐림', '눈', '기타', '비', '안개'], dtype=object)

 == 노면상태 ==


array(['건조', '젖음/습기', '기타', '서리/결빙', '적설', '해빙', '침수'], dtype=object)

 == 사고유형 ==


array(['차대사람', '차대차', '철길건널목', '차량단독'], dtype=object)

 == 사고유형 - 세부분류 ==


array(['횡단중', '기타', '측면충돌', '길가장자리구역통행중', '추돌', '차도통행중', '정면충돌', '후진중충돌',
       '보도통행중', '철길건널목', '공작물충돌', '전도전복 - 전도', '도로외이탈 - 추락', '도로외이탈 - 기타',
       '전도전복 - 전복'], dtype=object)

 == 법규위반 ==


array(['보행자보호의무위반', '직진우회전진행방해', '신호위반', '안전운전불이행', '중앙선침범', '과속',
       '안전거리미확보', '교차로운행방법위반', '차로위반', '기타', '불법유턴'], dtype=object)

 == 가해운전자 차종 ==


array(['승용', '기타불명', '이륜', '화물', '특수', '승합', '자전거', '원동기', '건설기계',
       '사륜오토바이(ATV)', '개인형이동수단(PM)', '농기계'], dtype=object)

 == 가해운전자 성별 ==


array(['남', '여', '기타불명'], dtype=object)

 == 가해운전자 연령 ==


array(['26세', '54세', '57세', '65세', '74세', '미분류', '47세', '59세', '29세',
       '25세', '22세', '55세', '33세', '23세', '71세', '17세', '28세', '36세',
       '44세', '24세', '53세', '27세', '56세', '43세', '30세', '77세', '49세',
       '31세', '51세', '58세', '41세', '45세', '64세', '68세', '48세', '38세',
       '60세', '50세', '62세', '39세', '61세', '67세', '21세', '73세', '46세',
       '52세', '66세', '32세', '20세', '35세', '78세', '75세', '63세', '34세',
       '88세', '82세', '40세', '72세', '19세', '37세', '69세', '70세', '16세',
       '18세', '42세', '86세', '76세', '79세', '80세', '87세', '84세', '81세',
       '14세', '83세', '15세', '85세', '12세', '90세 이상', '11세', '13세', '89세',
       '5세', '9세', '10세', '8세', '7세', '6세', '1세', '93세', '90세', '91세',
       '95세', '92세', '96세', '98세 이상', '94세', '97세', '4세'], dtype=object)

 == 가해운전자 상해정도 ==


array(['상해없음', '기타불명', '부상신고', '경상', '사망', '중상'], dtype=object)

 == 피해운전자 차종 ==


array(['보행자', '이륜', '승용', '화물', '특수', '자전거', '승합', '원동기', '사륜오토바이(ATV)',
       '기타불명', '건설기계', '농기계', '개인형이동수단(PM)', nan], dtype=object)

 == 피해운전자 성별 ==


array(['남', '여', '기타불명', nan], dtype=object)

 == 피해운전자 연령 ==


array(['40세', '20세', '17세', '10세', '56세', '27세', '30세', '31세', '60세',
       '67세', '69세', '32세', '51세', '71세', '61세', '19세', '24세', '26세',
       '35세', '18세', '39세', '46세', '54세', '50세', '66세', '47세', '37세',
       '28세', '62세', '72세', '45세', '34세', '59세', '36세', '29세', '38세',
       '70세', '49세', '57세', '58세', '76세', '75세', '33세', '64세', '52세',
       '44세', '73세', '63세', '42세', '22세', '65세', '48세', '53세', '23세',
       '43세', '25세', '68세', '41세', '55세', '78세', '79세', '8세', '80세',
       '21세', '74세', '86세', '4세', '11세', '77세', '84세', '85세', '7세', '83세',
       '6세', '미분류', '81세', '16세', '82세', '14세', '87세', '15세', '9세',
       '90세 이상', '3세', '88세', '5세', '12세', '13세', '2세', '1세', '89세',
       '91세', '90세', '97세', '93세', '92세', '94세', '96세', '95세', '98세 이상',
       nan], dtype=object)

 == 피해운전자 상해정도 ==


array(['경상', '중상', '사망', '상해없음', '기타불명', '부상신고', nan], dtype=object)

 == 사망자수 ==


array([0, 1, 2, 3, 4, 6, 5])

 == 중상자수 ==


array([ 0,  1,  2,  3,  4,  5,  6,  9, 12,  7,  8, 17, 15, 16, 10, 11, 13,
       19, 31])

 == 경상자수 ==


array([ 1,  0,  2,  5,  3,  4,  6, 12,  7,  8,  9, 10, 13, 15, 11, 19, 17,
       14, 23, 16, 21, 32, 20, 28, 22, 27, 18, 24, 41, 26, 38, 29, 40, 34,
       25])

 == 부상자수 ==


array([ 0,  1,  2,  3,  6,  5,  4,  9,  8,  7, 12, 10, 15, 14, 17, 13, 16,
       47, 29, 11, 20])

 == ECLO ==


array([  3,   5,  10,   7,   6,   4,   1,  11,   8,  15,   9,  12,  18,
        13,  23,  14,  56,  16,  22,  21,  17,  20,  34,   2,  19,  24,
        38,  25,  27,  39,  29,  40,  30,  26,  28,  89,  31,  36,  35,
        75,  33,  77,  53,  45,  54,  76,  70, 102,  43,  32,  37,  84,
        44,  81,  49,  94,  50,  46,  55, 141,  48,  47,  65,  41, 115,
        79,  57, 100,  64,  67,  88,  51,  71, 147,  63,  42,  82,  52,
        73, 133,  69,  59, 169,  62,  66,  58, 140,  86,  68,  80, 161,
        61, 142,  60,  96, 153, 104,  93,  78, 245, 117,  72,  95, 185,
        85,  74])

 == 월 ==


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

 == 일 ==


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

 == 시간 ==


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

 == 주야구분 ==


array(['야간', '주간'], dtype=object)

 == 피해운전자 연령대 ==


array(['40대', '20대', '10대', '50대', '30대', '60대', '70대', '10대 미만',
       '80대 이상'], dtype=object)

 == 피해운전자 구분 ==


array(['일반', '고령', '영유아'], dtype=object)

 == 가해운전자 연령대 ==


array(['20대', '50대', '60대', '70대', '80대 이상', '40대', '30대', '10대',
       '10대 미만'], dtype=object)

 == 가해운전자 구분 ==


array(['일반', '고령', '영유아'], dtype=object)

 == 시, 도 ==


array(['서울특별시', '경기도', '인천광역시', '충청남도', '광주광역시', '부산광역시', '강원도', '울산광역시',
       '전라북도', '경상남도', '경상북도', '전라남도', '충청북도', '대전광역시', '제주특별자치도',
       '세종특별자치시', '미분류', '대구광역시'], dtype=object)

 == 도로형태1 ==


array(['교차로 ', '기타 ', '단일로 ', '주차장 ', '미분류 '], dtype=object)

 == 도로형태2 ==


array([' 교차로횡단보도내', ' 교차로안', ' 기타', ' 교차로부근', ' 터널', ' 주차장', ' 고가도로위',
       ' 교량', ' 지하차도(도로)내', ' 미분류', ' 철길건널목'], dtype=object)

 == 계절 ==


array(['겨울', '봄', '여름', '가을'], dtype=object)

 == 사고 규모 ==


array(['소형', '중형', '대형'], dtype=object)

In [15]:
wrangiling(test)

       Shape      


(10963, 8)

        Info      
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10963 entries, 0 to 10962
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   ID      10963 non-null  object
 1   사고일시    10963 non-null  object
 2   요일      10963 non-null  object
 3   기상상태    10963 non-null  object
 4   시군구     10963 non-null  object
 5   도로형태    10963 non-null  object
 6   노면상태    10963 non-null  object
 7   사고유형    10963 non-null  object
dtypes: object(8)
memory usage: 685.3+ KB


None

      Columns     


Index(['ID', '사고일시', '요일', '기상상태', '시군구', '도로형태', '노면상태', '사고유형'], dtype='object')

        NaN       


ID      0
사고일시    0
요일      0
기상상태    0
시군구     0
도로형태    0
노면상태    0
사고유형    0
dtype: int64

    Duplicated    


Empty DataFrame
Columns: [ID, 사고일시, 요일, 기상상태, 시군구, 도로형태, 노면상태, 사고유형]
Index: []

    Description   


ID           사고일시     요일   기상상태           시군구      도로형태  \
count            10963          10963  10963  10963         10963     10963   
unique           10963           5548      7      5           192        11   
top     ACCIDENT_39609  2022-11-10 18    금요일     맑음  대구광역시 남구 대명동  단일로 - 기타   
freq                 1             10   1743  10321           422      5039   

         노면상태   사고유형  
count   10963  10963  
unique      6      3  
top        건조    차대차  
freq    10394   8559

      Unique      


ID      10963
사고일시     5548
요일          7
기상상태        5
시군구       192
도로형태       11
노면상태        6
사고유형        3
dtype: int64

In [16]:
unique_cols(data_set=test)

 == ID ==


array(['ACCIDENT_39609', 'ACCIDENT_39610', 'ACCIDENT_39611', ...,
       'ACCIDENT_50569', 'ACCIDENT_50570', 'ACCIDENT_50571'], dtype=object)

 == 사고일시 ==


array(['2022-01-01 01', '2022-01-01 04', '2022-01-01 06', ...,
       '2022-12-31 18', '2022-12-31 20', '2022-12-31 21'], dtype=object)

 == 요일 ==


array(['토요일', '일요일', '월요일', '화요일', '수요일', '목요일', '금요일'], dtype=object)

 == 기상상태 ==


array(['맑음', '흐림', '기타', '비', '눈'], dtype=object)

 == 시군구 ==


array(['대구광역시 수성구 상동', '대구광역시 수성구 지산동', '대구광역시 수성구 수성동2가',
       '대구광역시 수성구 신매동', '대구광역시 달서구 감삼동', '대구광역시 중구 달성동', '대구광역시 동구 신암동',
       '대구광역시 서구 평리동', '대구광역시 달서구 송현동', '대구광역시 달서구 두류동', '대구광역시 북구 매천동',
       '대구광역시 달서구 상인동', '대구광역시 달서구 진천동', '대구광역시 중구 삼덕동1가', '대구광역시 중구 동문동',
       '대구광역시 달서구 성당동', '대구광역시 북구 동천동', '대구광역시 북구 태전동', '대구광역시 남구 대명동',
       '대구광역시 달서구 대곡동', '대구광역시 북구 복현동', '대구광역시 달서구 본리동', '대구광역시 수성구 범어동',
       '대구광역시 수성구 황금동', '대구광역시 달서구 호산동', '대구광역시 중구 동인동1가', '대구광역시 남구 이천동',
       '대구광역시 달성군 유가읍', '대구광역시 달서구 월암동', '대구광역시 북구 동호동', '대구광역시 달서구 죽전동',
       '대구광역시 달서구 본동', '대구광역시 달서구 도원동', '대구광역시 달성군 다사읍', '대구광역시 달서구 용산동',
       '대구광역시 달서구 유천동', '대구광역시 북구 산격동', '대구광역시 달서구 파호동', '대구광역시 동구 효목동',
       '대구광역시 북구 고성동3가', '대구광역시 중구 남산동', '대구광역시 동구 지묘동', '대구광역시 달성군 하빈면',
       '대구광역시 서구 내당동', '대구광역시 수성구 매호동', '대구광역시 북구 침산동', '대구광역시 동구 신천동',
       '대구광역시 동구 방촌동', '대구광역시 수성구 두산동', '대구광역시 달성군 구지면', '대구광역시 달서구 대천동',
       '대구광역시 달서구 월성동', '대구광역시 달성군 화원읍', '대구광역시 북구 고성동2가',

 == 도로형태 ==


array(['교차로 - 교차로안', '단일로 - 기타', '교차로 - 교차로횡단보도내', '교차로 - 교차로부근',
       '단일로 - 지하차도(도로)내', '기타 - 기타', '단일로 - 교량', '단일로 - 고가도로위',
       '주차장 - 주차장', '단일로 - 터널', '미분류 - 미분류'], dtype=object)

 == 노면상태 ==


array(['건조', '젖음/습기', '서리/결빙', '기타', '침수', '적설'], dtype=object)

 == 사고유형 ==


array(['차대사람', '차대차', '차량단독'], dtype=object)

## Data Preprocessing for Modeling

In [17]:
test = test.drop("ID", axis = 1)

In [18]:
# train data의 columns 구성과 같게 만들어주는 작업

test["date_time"] = pd.to_datetime(test['사고일시'])
test['월'] = test.date_time.dt.month
test['일'] = test.date_time.dt.day
test['시간'] = test.date_time.dt.hour
test = test.drop(["사고일시"], axis = 1)
test = test.drop(["date_time"], axis = 1)

In [19]:
# 주, 야 구분 (6시~17시 주간, 18시~5시 야간)
test["주야구분"]=np.where(test["시간"].isin(range(6, 18)), "주간", "야간")
test

요일 기상상태              시군구         도로형태 노면상태  사고유형   월   일  시간 주야구분
0      토요일   맑음     대구광역시 수성구 상동   교차로 - 교차로안   건조  차대사람   1   1   1   야간
1      토요일   맑음    대구광역시 수성구 지산동     단일로 - 기타   건조  차대사람   1   1   1   야간
2      토요일   맑음  대구광역시 수성구 수성동2가   교차로 - 교차로안   건조   차대차   1   1   4   야간
3      토요일   맑음    대구광역시 수성구 신매동     단일로 - 기타   건조   차대차   1   1   4   야간
4      토요일   맑음    대구광역시 달서구 감삼동   교차로 - 교차로안   건조   차대차   1   1   6   주간
...    ...  ...              ...          ...  ...   ...  ..  ..  ..  ...
10958  토요일   맑음     대구광역시 남구 대명동     단일로 - 터널   건조   차대차  12  31  18   야간
10959  토요일   맑음    대구광역시 수성구 시지동     단일로 - 기타   건조   차대차  12  31  18   야간
10960  토요일   맑음    대구광역시 수성구 연호동     단일로 - 기타   건조   차대차  12  31  20   야간
10961  토요일   맑음    대구광역시 수성구 범물동  교차로 - 교차로부근   건조   차대차  12  31  20   야간
10962  토요일   맑음     대구광역시 동구 효목동  교차로 - 교차로부근   건조   차대차  12  31  21   야간

[10963 rows x 10 columns]

In [20]:
# def split_age(age):
#     if age != np.nan:
#         if age < 10:
#             return "10대 미만"
#         elif age < 20:
#             return "10대"

#         elif age < 30:
#             return "20대"

#         elif age < 40:
#             return "30대"

#         elif age < 50:
#             return "40대"

#         elif age < 60:
#             return "50대"

#         elif age < 70:
#             return "60대"

#         elif age < 80:
#             return "70대"

#         else:
#             return "80대 이상"
#     else:
#         return "미분류"

In [21]:
# def age_category(age):
#         if age != np.nan:
#             if age < 10 :
#                 return "영유아"
#             elif age < 60 :
#                 return "일반"
#             else :
#                 return "고령"
#         else:
#              return "미분류"

In [22]:
# def age_add_variable(data:pd.DataFrame, age_col:str):
#     pattern = r'(\d+)'
#     data["temp"] = data[age_col].str.extract(pattern).astype(float)
#     data[age_col[:6]+"연령대"] = data["temp"].apply(split_age)
#     data[age_col[:6]+"구분"] = data["temp"].apply(age_category)
#     data.drop(["temp"], axis = 1, inplace = True)

In [23]:
# 연령대와 연령대에 따른 구분 # 연령이 안나와있어서 할 수 없음
# age_add_variable(data=test, age_col="피해운전자 연령")
# age_add_variable(data=test, age_col="가해운전자 연령")

In [24]:
# location extraction
def process_location_data(df, address_column, drop_columns):
    location_pattern = r'(\S+) (\S+)'
    df[['시,도', 'temp']] = df[address_column].str.extract(location_pattern)
    df = df.drop(['temp'], axis=1)
    df = df.drop(drop_columns, axis=1)
    return df

In [25]:
# 시, 도 구분 해봤자 대구광역시라 필요없음
# process_location_data(test, "시군구", "시군구")

In [26]:
test = test.drop("시군구", axis=1)

In [27]:
# 도로형태를 나눔
test[["도로형태1", "도로형태2"]] = test["도로형태"].str.split("-", expand=True)
test = test.drop(["도로형태"], axis=1)

In [28]:
def make_season (month):
    if 3 <= month and month <= 5:
        return "봄"
    elif 6 <= month and month <= 8:
        return "여름"
    elif 9 <= month and month <= 11:
        return "가을"
    else:
        return "겨울"

In [29]:
# 파생변수 "계절" 추가
test["계절"] = test["월"].apply(make_season)

In [30]:
# def accident_size(ECLO):
#     if ECLO < 5 :
#         return "소형"
#     elif 5 <= ECLO and ECLO <= 10 :
#         return "중형"
#     else :
#         return "대형"

In [31]:
# 사고 규모는 ECLO를 기반으로 작성하므로 test에서는 만들 수 없음
# test["사고 규모"] = test["ECLO"].apply(accident_size)

In [32]:
train

ID   요일 기상상태 노면상태  사고유형 사고유형 - 세부분류  \
0       COUNTRYWIDE_ACCIDENT_000000  화요일   맑음   건조  차대사람         횡단중   
1       COUNTRYWIDE_ACCIDENT_000001  화요일   맑음   건조   차대차          기타   
2       COUNTRYWIDE_ACCIDENT_000002  화요일   맑음   건조   차대차        측면충돌   
3       COUNTRYWIDE_ACCIDENT_000003  화요일   맑음   건조  차대사람         횡단중   
4       COUNTRYWIDE_ACCIDENT_000004  화요일   맑음   건조   차대차        측면충돌   
...                             ...  ...  ...  ...   ...         ...   
616550               ACCIDENT_39604  금요일   맑음   건조   차대차        측면충돌   
616551               ACCIDENT_39605  금요일   맑음   건조   차대차        측면충돌   
616552               ACCIDENT_39606  금요일   맑음   건조   차대차        측면충돌   
616553               ACCIDENT_39607  금요일   맑음   건조   차대차          추돌   
616554               ACCIDENT_39608  금요일   맑음   건조   차대차        측면충돌   

             법규위반 가해운전자 차종 가해운전자 성별 가해운전자 연령  ... 주야구분 피해운전자 연령대 피해운전자 구분  \
0       보행자보호의무위반       승용        남      26세  ...   야간       40대       일반   
1       직진우회전진행방해       승용        남      54세  ...   야간       20대       일반   
2            신호위반       승용        여      57세  ...   야간       10대       일반   
3       보행자보호의무위반       승용        여      65세  ...   야간       10대       일반   
4            신호위반       승용        여      74세  ...   야간       50대       일반   
...           ...      ...      ...      ...  ...  ...       ...      ...   
616550       신호위반       승용        여      52세  ...   야간       20대       일반   
616551    안전거리미확보       승용        여      60세  ...   야간       50대       일반   
616552  교차로운행방법위반       승용        남      60세  ...   야간       70대       고령   
616553    안전운전불이행       승용        남      40세  ...   야간       50대       일반   
616554    안전운전불이행       승용        남      27세  ...   야간       30대       일반   

       가해운전자 연령대 가해운전자 구분   시, 도  도로형태1       도로형태2  계절  사고 규모  
0            20대       일반  서울특별시   교차로     교차로횡단보도내  겨울     소형  
1            50대       일반    경기도   교차로         교차로안  겨울     소형  
2            50대       일반    경기도   교차로         교차로안  겨울     중형  
3            60대       고령    경기도    기타           기타  겨울     중형  
4            70대       고령  인천광역시   교차로         교차로안  겨울     중형  
...          ...      ...    ...    ...         ...  ..    ...  
616550       50대       일반  대구광역시   교차로         교차로안  겨울     소형  
616551       60대       고령  대구광역시   단일로           기타  겨울     소형  
616552       60대       고령  대구광역시   교차로         교차로안  겨울     중형  
616553       40대       일반  대구광역시    기타           기타  겨울     소형  
616554       20대       일반  대구광역시   단일로    지하차도(도로)내  겨울     중형  

[616555 rows x 33 columns]

In [33]:
test

요일 기상상태 노면상태  사고유형   월   일  시간 주야구분 도로형태1   도로형태2  계절
0      토요일   맑음   건조  차대사람   1   1   1   야간  교차로     교차로안  겨울
1      토요일   맑음   건조  차대사람   1   1   1   야간  단일로       기타  겨울
2      토요일   맑음   건조   차대차   1   1   4   야간  교차로     교차로안  겨울
3      토요일   맑음   건조   차대차   1   1   4   야간  단일로       기타  겨울
4      토요일   맑음   건조   차대차   1   1   6   주간  교차로     교차로안  겨울
...    ...  ...  ...   ...  ..  ..  ..  ...   ...     ...  ..
10958  토요일   맑음   건조   차대차  12  31  18   야간  단일로       터널  겨울
10959  토요일   맑음   건조   차대차  12  31  18   야간  단일로       기타  겨울
10960  토요일   맑음   건조   차대차  12  31  20   야간  단일로       기타  겨울
10961  토요일   맑음   건조   차대차  12  31  20   야간  교차로    교차로부근  겨울
10962  토요일   맑음   건조   차대차  12  31  21   야간  교차로    교차로부근  겨울

[10963 rows x 11 columns]

In [34]:
# test에 있는 columns만 사용

test.columns

Index(['요일', '기상상태', '노면상태', '사고유형', '월', '일', '시간', '주야구분', '도로형태1', '도로형태2',
       '계절'],
      dtype='object')

In [35]:
use_columns = ['요일', '기상상태', '노면상태', '사고유형', '월', '일', '시간', '주야구분', '도로형태1', '도로형태2', '계절', 'ECLO']

In [36]:
train = train[use_columns]
train

요일 기상상태 노면상태  사고유형   월   일  시간 주야구분 도로형태1       도로형태2  계절  ECLO
0       화요일   맑음   건조  차대사람   1   1   0   야간  교차로     교차로횡단보도내  겨울     3
1       화요일   맑음   건조   차대차   1   1   0   야간  교차로         교차로안  겨울     3
2       화요일   맑음   건조   차대차   1   1   0   야간  교차로         교차로안  겨울     5
3       화요일   맑음   건조  차대사람   1   1   0   야간   기타           기타  겨울    10
4       화요일   맑음   건조   차대차   1   1   0   야간  교차로         교차로안  겨울     7
...     ...  ...  ...   ...  ..  ..  ..  ...   ...         ...  ..   ...
616550  금요일   맑음   건조   차대차  12  31  19   야간  교차로         교차로안  겨울     3
616551  금요일   맑음   건조   차대차  12  31  19   야간  단일로           기타  겨울     3
616552  금요일   맑음   건조   차대차  12  31  21   야간  교차로         교차로안  겨울    10
616553  금요일   맑음   건조   차대차  12  31  22   야간   기타           기타  겨울     3
616554  금요일   맑음   건조   차대차  12  31  23   야간  단일로    지하차도(도로)내  겨울     6

[616555 rows x 12 columns]

In [37]:
# 데이터 확인 작업

In [38]:
train.isna().sum()

요일       0
기상상태     0
노면상태     0
사고유형     0
월        0
일        0
시간       0
주야구분     0
도로형태1    0
도로형태2    0
계절       0
ECLO     0
dtype: int64

In [39]:
test.isna().sum()

요일       0
기상상태     0
노면상태     0
사고유형     0
월        0
일        0
시간       0
주야구분     0
도로형태1    0
도로형태2    0
계절       0
dtype: int64

## Modeling

In [40]:
# # Define a function to calculate RMSLE
# from sklearn.metrics import make_scorer
# def rmsle(y_true, y_pred):
#     return np.sqrt(np.mean(np.square(np.log1p(y_pred) - np.log1p(y_true))))

# # # Create a scorer for RMSLE
# # rmsle_scorer = make_scorer(rmsle, greater_is_better=False)

In [41]:
train.columns

Index(['요일', '기상상태', '노면상태', '사고유형', '월', '일', '시간', '주야구분', '도로형태1', '도로형태2',
       '계절', 'ECLO'],
      dtype='object')

In [46]:
exp = setup(session_id=42, data=train, train_size=0.8, fold_shuffle=True, data_split_shuffle=True)

In [49]:
best_model = compare_models(n_select=25, sort='RMSLE', include = ['lasso', 'ridge', 'lightgbm', 'xgboost', 'catboost', 'dt', 'lr', 'rf', 'gbr'])

Processing:   0%|          | 0/49 [00:00<?, ?it/s]

from matplotlib import pyplot as plt
import seaborn as sns
_df_0.groupby('  ').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

In [53]:
lightgbm_model = create_model('lightgbm')

Processing:   0%|          | 0/4 [00:00<?, ?it/s]

In [54]:
catboost_model = create_model('catboost')

Processing:   0%|          | 0/4 [00:00<?, ?it/s]

In [55]:
gbr_model = create_model('gbr')

Processing:   0%|          | 0/4 [00:00<?, ?it/s]

In [56]:
xgboost_model = create_model('xgboost')

Processing:   0%|          | 0/4 [00:00<?, ?it/s]

In [58]:
ridge_model = create_model('ridge')

Processing:   0%|          | 0/4 [00:00<?, ?it/s]

In [61]:
lightgbm_tuned_model = tune_model(lightgbm_model, n_iter = 5, optimize='RMSLE')
catboost_tuned_model = tune_model(catboost_model, n_iter = 5, optimize='RMSLE')
gbr_tuned_model = tune_model(gbr_model, n_iter = 5, optimize='RMSLE')
xgboost_tuned_model = tune_model(xgboost_model, n_iter = 5, optimize='RMSLE')
ridge_tuned_model = tune_model(ridge_model, n_iter = 5, optimize='RMSLE')

Processing:   0%|          | 0/7 [00:00<?, ?it/s]

Fitting 10 folds for each of 5 candidates, totalling 50 fits


Original model was better than the tuned model, hence it will be returned. NOTE: The display metrics are for the tuned model (not the original one).


Processing:   0%|          | 0/7 [00:00<?, ?it/s]

Fitting 10 folds for each of 5 candidates, totalling 50 fits


Processing:   0%|          | 0/7 [00:00<?, ?it/s]

Fitting 10 folds for each of 5 candidates, totalling 50 fits


Processing:   0%|          | 0/7 [00:00<?, ?it/s]

Fitting 10 folds for each of 5 candidates, totalling 50 fits


Processing:   0%|          | 0/7 [00:00<?, ?it/s]

Fitting 10 folds for each of 5 candidates, totalling 50 fits


Original model was better than the tuned model, hence it will be returned. NOTE: The display metrics are for the tuned model (not the original one).


In [62]:
blender5_model = blend_models(estimator_list=[lightgbm_tuned_model,
                                              catboost_tuned_model,
                                              gbr_tuned_model,
                                              xgboost_tuned_model,
                                              ridge_tuned_model])

Processing:   0%|          | 0/6 [00:00<?, ?it/s]

In [63]:
final_model = finalize_model(blender5_model)

In [70]:
prediction = predict_model(final_model, data = test)

In [71]:
prediction

요일 기상상태 노면상태  사고유형   월   일  시간 주야구분 도로형태1   도로형태2  계절  \
0      토요일   맑음   건조  차대사람   1   1   1   야간  교차로     교차로안  겨울   
1      토요일   맑음   건조  차대사람   1   1   1   야간  단일로       기타  겨울   
2      토요일   맑음   건조   차대차   1   1   4   야간  교차로     교차로안  겨울   
3      토요일   맑음   건조   차대차   1   1   4   야간  단일로       기타  겨울   
4      토요일   맑음   건조   차대차   1   1   6   주간  교차로     교차로안  겨울   
...    ...  ...  ...   ...  ..  ..  ..  ...   ...     ...  ..   
10958  토요일   맑음   건조   차대차  12  31  18   야간  단일로       터널  겨울   
10959  토요일   맑음   건조   차대차  12  31  18   야간  단일로       기타  겨울   
10960  토요일   맑음   건조   차대차  12  31  20   야간  단일로       기타  겨울   
10961  토요일   맑음   건조   차대차  12  31  20   야간  교차로    교차로부근  겨울   
10962  토요일   맑음   건조   차대차  12  31  21   야간  교차로    교차로부근  겨울   

       prediction_label  
0              4.464509  
1              4.283347  
2              5.548768  
3              5.381038  
4              5.336191  
...                 ...  
10958          6.661228  
10959          5.025676  
10960          5.037821  
10961          4.999044  
10962          5.034416  

[10963 rows x 12 columns]

In [82]:
nice = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/data/deacu_car_accident/35.csv")
nice

ID      ECLO
0      ACCIDENT_39609  3.762969
1      ACCIDENT_39610  3.446971
2      ACCIDENT_39611  4.614977
3      ACCIDENT_39612  4.096889
4      ACCIDENT_39613  4.441886
...               ...       ...
10958  ACCIDENT_50567  4.753187
10959  ACCIDENT_50568  4.383807
10960  ACCIDENT_50569  4.846968
10961  ACCIDENT_50570  4.727992
10962  ACCIDENT_50571  4.628516

[10963 rows x 2 columns]

In [83]:
import math

pred = pd.DataFrame({
    "ECLO" : prediction["prediction_label"],
    "ECLO-Best" : nice["ECLO"],
    "ECLO-Round UP" : prediction["prediction_label"].apply(math.ceil),
    "ECLO-Round Down" : prediction["prediction_label"].apply(math.floor),
    "ECLO-Round" : prediction["prediction_label"].apply(round)
    })

In [84]:
pred

ECLO  ECLO-Best  ECLO-Round UP  ECLO-Round Down  ECLO-Round
0      4.464509   3.762969              5                4           4
1      4.283347   3.446971              5                4           4
2      5.548768   4.614977              6                5           6
3      5.381038   4.096889              6                5           5
4      5.336191   4.441886              6                5           5
...         ...        ...            ...              ...         ...
10958  6.661228   4.753187              7                6           7
10959  5.025676   4.383807              6                5           5
10960  5.037821   4.846968              6                5           5
10961  4.999044   4.727992              5                4           5
10962  5.034416   4.628516              6                5           5

[10963 rows x 5 columns]

In [85]:
pred.to_excel("my_model_score.xlsx")